language: python
sudo: false
addons:
  apt:
    packages:
    - python-numpy
    - python-matplotlib
    - python-pip
    - python-coverage
    - xvfb # For mayavi headless

virtualenv:
        system_site_packages: true

env:
    matrix:
        - DISTRIB="ubuntu" PYTHON_VERSION="2.7"
        # This environment tests the oldest supported anaconda env
        - DISTRIB="conda" PYTHON_VERSION="2.6"
        # This environment tests is for mayavi
        - DISTRIB="conda" PYTHON_VERSION="2.7"
        # This environment tests the newest supported anaconda env
        - DISTRIB="conda" PYTHON_VERSION="3.4"

before_install:
    - if [ "$DISTRIB" == "conda" ]; then
         wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
         chmod +x miniconda.sh;
         ./miniconda.sh -b;
         export PATH=/home/travis/miniconda2/bin:$PATH;
         conda update --yes conda;
      fi

install:
    - if [ "$DISTRIB" == "conda" ]; then
        conda create --yes -n testenv python=$PYTHON_VERSION pip numpy
        setuptools matplotlib pillow sphinx nose coverage;
        source activate testenv;
        if [ "$PYTHON_VERSION" == "2.7" ]; then
          conda install --yes --quiet mayavi;
          conda upgrade --yes --all;
          # virtual framebuffer for mayavi rendering
          Xvfb :1 -screen 0 1280x1024x24 -auth localhost &
          export DISPLAY=:1
        fi;
      fi;
    - pip install -r requirements.txt
    - python setup.py install

script:
    - if [ "$DISTRIB" == "ubuntu" ]; then python setup.py nosetests; fi
    - if [ "$DISTRIB" == "conda" ]; then nosetests; fi
    - cd doc
    - make html
