language: python

python:
    - "2.7"

before_install:

install:
    - pip install -q sphinx pillow matplotlib scipy scikit-learn
    - python setup.py install

script:
    - python setup.py nosetests
