language: python

python:
    - "2.7"
    - "3.4"

virtualenv:
        system_site_packages: true

before_install:
    - sudo apt-get install -qq python-numpy python-matplotlib python-sphinx

install:
    - pip install -r requirements.txt
    - python setup.py install

script:
    - python setup.py nosetests
